namespace :studio_tasks do

  desc "Calls the API for studios"

  task fetch_classes: :environment do
    MbApi.call_mind_body
    MbApi.call_mind_body(true)
  end
  task fill_studios: :environment do
    user_ids = User.all.pluck(:id) #select all user's id and fetch their id's to create studios
    user_ids.each do |user_id|
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 7499, studio_name: "Studio Clinic",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 8981, studio_name: "Energize & Recharge Pilates",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 11915, studio_name: "Myers Place",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 13772, studio_name: "Acumotum",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 15947, studio_name: "Kundalini House",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 22181, studio_name: "Skulpt Personal Training",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 40076, studio_name: "5th Element Wellness",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 45855, studio_name: "Dynamic Boxing Fitness",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 49693, studio_name: "The Yoga Place - Melbourne",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 132145, studio_name: "F45 Training - Hawthorn",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 138937, studio_name: "Pilates on Bourke ",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 139876, studio_name: "The Yoga Social",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 141803, studio_name: "PITFIT Fitness Made FUNctional!",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 145655, studio_name: "The Collective Yoga and Pilates Studio",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 153337, studio_name: "Take Shape",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 154116, studio_name: "Fitas Personal Training",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 162233, studio_name: "Rise Yoga ",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 174308, studio_name: "Aleenta Barre - Flinders Lane Melbourne",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 176168, studio_name: "North Yoga Studio",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 176561, studio_name: "Loudy Wiggins Fitness",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 180093, studio_name: "Cycle Collective",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 180954, studio_name: "South Melbourne Personal Training",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 188149, studio_name: "Stiles Training",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 190825, studio_name: "Princes Park Boot Camp",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 191424, studio_name: "Productive Health and Wellness",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 203989, studio_name: "Yoga Dance Moves",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 210686, studio_name: "Hello Flexi",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 211141, studio_name: "F45 Training South Melbourne",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 218871, studio_name: "Together Fit",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 222038, studio_name: "Bridge Fitness",description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
      Studio.find_or_create_by(logo: "", user_id: user_id, site_ids: 230675, studio_name: "Phoenix Dance Studio", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio ducimus, necessitatibus sed reiciendis. Ducimus nam nemo repellendus magnam quo fugiat dolore, eligendi expedita explicabo veniam veritatis debitis ullam reprehenderit neque!")
    end
    #Studio collection with site_ids from MindBody Api Database
 end
end

# heroku run rake studio_tasks:fetch_classes
# bundle exec rake studio_tasks:fetch_classes